Tip44 Adding dir and file
saucelabs/elemental-next pull request #182
Opened 2023-03-15 19:28 UTC by Roseywinter

Tip44 Adding dir and file
-  Fixed broken link referencing expected conditions
-  Added a new example with instructions that includes a wait with the following codes:
```def wait_for(seconds)
  Selenium::WebDriver::Wait.new(timeout: seconds).until { yield }
end
```
and (just before `expect` line):
`wait_for(10) { @driver.find_element(css: '.icon-2x').displayed? }`

-  All code ran as expected after edits.

2023-03-16 00:29 UTC, aquaomarine requested changes

2023-03-16 00:29 UTC, aquaomarine commented on frontend/docs/updated-tips/44-exception-handling/ruby.md
> +
Looks like a Use Case is missing

2023-03-17 00:51 UTC, Roseywinter commented on frontend/docs/updated-tips/44-exception-handling/ruby.md
> +
Added

2023-03-17 01:24 UTC, aquaomarine approved these changes

2023-03-17 15:40 UTC, merged