created javascript file
saucelabs/elemental-next pull request #193
Opened 2023-03-15 23:58 UTC by janackeh

created new javascript file in updated tips

2023-03-16 03:54 UTC, aquaomarine commented on frontend/docs/updated-tips/12-opt-out-of-ab-tests/javascript.md
> +title: "How To Opt-out of A/B Tests"
Title needs to be changed to Javascript

2023-03-16 03:56 UTC, aquaomarine requested changes
Good to merge after title change!

2023-03-17 00:53 UTC, Roseywinter approved these changes

2023-03-17 00:54 UTC, Roseywinter commented
> Good to merge after title change!

Fixed. Good to merge.

2023-03-17 01:29 UTC, aquaomarine approved these changes

2023-03-17 17:49 UTC, merged