Pull Request Template draft
saucelabs/elemental-next pull request #481
Opened 2023-05-01 23:19 UTC by Roseywinter

This a pull request template draft... looking for some feedback. :)

2023-05-02 01:33 UTC, aquaomarine approved these changes

2023-05-02 10:02 UTC, discombobulateme requested changes
Hey! How hard is it to create a template? 😅
Some notes:

- the template itself should be straightforward, help people to be as direct and informative as possible to help the reviewer. Think about placeholders that help you start writting
- all the explanation content should be in the contribution guidelines, which people should read before contributing and making a PR
- Checklists are awesome! Type of contribution. One thought on that one... shall we have different templates for different types of contributions? [This example ](https://github.com/forem/forem/blob/main/.github/PULL_REQUEST_TEMPLATE.md)uses one single generic template and you use the checkbox so say which type. It bothers me that it gets toooooo texty but, [this example](https://dev.to/opensauced/how-to-create-a-good-pull-request-template-and-why-you-should-add-gifs-4i0l), although texty, its nicer, as you are doing, it adds graphics
- [This](https://axolo.co/blog/p/part-3-github-pull-request-template) gives different templates structure to different types of template
- On the 2nd checklist, the 2 last items are unnecessary. You do not ship broken code, never. It can be unfinished, but it means its out of the scope. Draft is a function, it will not be reviewed anyway while a draft.  Check the link above to see other checklists

my heart for including accessibility <3

2023-05-02 21:07 UTC, Roseywinter commented
Made some changes to the PR Template. Is it coming along better @discombobulateme ?

Changes made:
- Removed some excess wording, and commented out some lines.
- Improved some of the checklist flows
- Included section about testing
- Improved section about related issues

2023-05-03 17:36 UTC, discombobulateme approved these changes

2023-05-03 17:36 UTC, discombobulateme commented on .github/pull_request_template.md
> +-  This is a linked PR that will close Issue #
Delete this

2023-05-03 17:43 UTC, Roseywinter commented on .github/pull_request_template.md
> +-  This is a linked PR that will close Issue #
Done! :)

2023-05-03 17:43 UTC, merged